apiVersion: v1
kind: ConfigMap
metadata:
  name: smtp-configmap
data:
  host: {{index . "host" | b64enc}}
  secure: {{index . "secure" | b64enc}}
  port: {{index . "port" | toString | b64enc}}
  domain: {{index . "domain" | b64enc}}
