apiVersion: v1
kind: Secret
metadata:
  name: smtp-secret
type: Opaque
stringData:
  host: {{index . "host"}}
  secure: {{index . "secure"}}
  port: {{index . "port" | toString}}
  username: {{index . "smtpUsername"}}
  password: {{index . "smtpPassword"}}
