apiVersion: v1
kind: Secret
metadata:
  name: smtp-secret
type: Opaque
stringData:
  host: {{index . "host"}}
  secure: {{index . "secure"}}
  port: {{quote (index . "port")}}
  username: {{index . "smtpUsername"}}
  password: {{index . "smtpPassword"}}
